box_name: local_box
slack_hook_url: https://hooks.slack.com/services/abc
proxy_list:
  - destination_address: ya.ru
    destination_port: 42123
    notify_http: true
    listen_port: 8000
  - destination_address: 127.0.0.1
    destination_port: 4001
    notify_http: true
    listen_port: 4000